### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by damla** [patika-hepsiburada-react-bootcamp/odev-2-damla#1]
# Description

- Design a UI contains MVP components.

# To-Dos

- [x] Add assets for hangman in JPEG format.
- [ ] Create components.
   - [x] Header
      - [x] Logo
      - [x] Game Name
      - [x] Score
      - [ ] Reset Button
   - [ ] Section
      - [ ] Content
         - [ ] Word
            - [ ] Character
         - [ ] Keyboard
            - [ ] Key
      - [ ] Image
      - [ ] Audio ( public chanting ) => incremental sound
   - [ ] Footer
      - [ ] [Clou](https://clou.shop) ads.
      - [x] Made with ❤️ by damla

# Prototype

<img width="764" alt="ui-design" src="https://user-images.githubusercontent.com/24878421/135726770-20718e51-b780-4190-8b59-8fad12f80846.png">
